"""Buat hapus cascade

Revision ID: 8761fc573e58
Revises: 04b4db4d61d6
Create Date: 2023-03-10 10:57:13.921471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8761fc573e58'
down_revision = '04b4db4d61d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('dosen_satu',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('dosen_dua',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.create_foreign_key(None, 'dosen', ['dosen_satu'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('dosen_dua',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('dosen_satu',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
