"""Update table user

Revision ID: 993dae816297
Revises: 8761fc573e58
Create Date: 2023-03-10 16:08:17.881917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993dae816297'
down_revision = '8761fc573e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
