"""Buat Schema Gambar

Revision ID: ef406d65f42c
Revises: b4f590cf21da
Create Date: 2023-03-14 16:45:00.765678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef406d65f42c'
down_revision = 'b4f590cf21da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gambar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judul', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('pathname', sa.String(length=200), nullable=False))
        batch_op.drop_column('alamat')
        batch_op.drop_column('nidn')
        batch_op.drop_column('nama')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gambar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=13), nullable=False))
        batch_op.add_column(sa.Column('nama', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('nidn', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('alamat', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('pathname')
        batch_op.drop_column('judul')

    # ### end Alembic commands ###
